### ISSUE TITLE
[BUG] PD Radar persists on leaving car

### ISSUE THREAD

**Issue by jplink420** [ParadoxGamingRP/bugs-and-suggestions#1750]
### Your Discord Name

j_plink

### A clear and concise description of what the bug is

When you get out of your PD car and have your radar turned on, the radar will stay stuck on the bottom of your screen when you get out of the car. This is irritating as it gets in the way of the PD camera, as well as is just annoying to have in the corner of your screen when on foot. 

### Steps to Reproduce the Bug

1. Get into a PD car
2. Turn on your radar
3. Get out of your PD car
4. Radar will still be stuck in your eye

### Expected Behavior

For my radar to disappear when I get out of my car. 

### Screenshots/Videos

https://i.imgur.com/RB2PhyA.jpeg

### Log File

[CitizenFX_log_2023-08-29T080403.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12462288/CitizenFX_log_2023-08-29T080403.log)

**Comment by JnKTechstuff** [comment]
Fixed

**Comment by M1ngh** [comment]
The issue is not fixed yet and after you get out of the car with it he is also not marking any speed and plates.

ill drop a video below and my log

https://medal.tv/games/gta-v/clips/1rtNQ1GU4fRPH7/d1337dCoDOOG?invite=cr-MSwwM20sMzgwMzUxODEs

[CitizenFX_log_2023-08-29T195620.log](https://github.com/ParadoxGamingRP/bugs-and-suggestions/files/12468971/CitizenFX_log_2023-08-29T195620.log)
