### ISSUE TITLE
[BUG] Diamond Unable to be Targeted for mining job

### ISSUE THREAD

**Issue by H0lyPika** [ParadoxGamingRP/bugs-and-suggestions#566]
### Your Discord Name

HolyPika#9815

### A clear and concise description of what the bug is

being unable to target the New diamond using your thirdeye plus it not getting a real entity so your able to walk right through it

### Steps to Reproduce the Bug

spawn a diamond using the new skin inside of the mines

### Expected Behavior

I would be able to mine the Diamond Ore using my third eye and received a diamond from the ore vein

### Screenshots/Videos

![image](https://user-images.githubusercontent.com/109408822/179344539-85e2d038-9d13-4bca-83b0-3535bca44e8b.png)
![image](https://user-images.githubusercontent.com/109408822/179344554-1eb60aca-a088-4c44-b0c6-f1a6c597bb67.png)

### Log File
[CitizenFX_log_2022-07-16T061631.log](https://github.com/ParadoxGamingRP/paradox-bugs/files/9125351/CitizenFX_log_2022-07-16T061631.log)

**Comment by JnKTechstuff** [comment]
Should be fixed

**Comment by xXJamieXx** [comment]
Issue is still happening.

**Comment by H0lyPika** [comment]
Problem is fixed and I'm able to mine the Diamond ore now, but the models image does not sit on top of where the Ore spawned

**Comment by xXJamieXx** [comment]
@ithegreatgatsby Confirmed this was still an issue yesterday.

**Comment by ithegreatgatsby** [comment]
@xXJamieXx Yeah the placement of the prop compared to the third eye location is pretty far off https://streamable.com/zzok49

**Comment by CorFinn** [comment]
New prop created, with sparkly diamonds inside!
Should be fixed next update!
